### ISSUE TITLE
Loading a CSV file doesn't seem to work

### ISSUE THREAD

**Issue by domoritz** [cmudig/mosaic-profiler#29]
I tried the online version with a CSV file but nothing seems to happen. I'd suggest

* make it clear what file types are supported
* adding error handling if there isn't yet
* add a button to load an example dataset just to experiment with the UI

**Comment by JessamineQ** [comment]
I believe the CSV file wasn't loading properly since the database had not finished initializing, so I added a loading screen as well as an example button in #34 . Let me know if the file still isn't loading, thank you!

**Comment by domoritz** [comment]
Works now
